### ISSUE TITLE
No methods for introspecting over the mappings

### ISSUE THREAD

**Issue by phillord** [endoli/curie.rs#1]
I am using this library in a parser, and it's difficult to test, because there is no mechanism to introspect over the mappings that a PrefixMapping has. I had to resort to using transmute to break the privacy restrictions.

Nice library!

**Comment by waywardmonkeys** [comment]
I forgot to watch my own project, so I missed this issue. Sorry!

Looks like I could just make the `mapping` pub ... or add a function `mappings` that returns an iter ... or do you have another preference?

What sort of testing are you doing?

**Comment by phillord** [comment]
Either of these two options seems fine. No idea which is the best -- I am new at rust so do not feel fit to choose.

My tests look like this: https://github.com/phillord/horned-owl/blob/54a5b97d342d6d7504bbee654dbeec3b28f0f2cc/src/io/reader.rs#L192

I'm writing a parser and want to see if it's worked. As before, my rust programming is still in the "try anything till it works" stage.

**Comment by waywardmonkeys** [comment]
I've pushed a `v0.0.5` release that adds a `PrefixMapping::mappings()` method that returns the iterator. Let me know if that helps or something more or different is needed.

Also, I think we should talk more ... I want a lot more of an RDF stack in Rust. :)
