### ISSUE TITLE
String to Curie method

### ISSUE THREAD

**Issue by phillord** [endoli/curie.rs#2]
At the moment you have methods for going from Curie to IRI, but there is not method from going from a string to a curie. So, I can use this for parsing, but not for rendering!

Would it be possible to add this?

**Comment by waywardmonkeys** [comment]
I think you meant for going from a Curie to a string, since you mentioned rendering ... if so, I've fixed this and published a new release (`0.0.6`).

If not, then please re-open with more detail.

**Comment by phillord** [comment]
Sorry, if I wasn't clear. Given a string, I need to generate a curie.  In memory I am storing an ontology with entities stored as an IRI (since the IRI is the thing, while the curie is an feature of the serialisation). When I serialize, I need to go back from a string to a curie, based on a prefix mapper of some sort.

I can send a PR if you like!

**Comment by waywardmonkeys** [comment]
A PR sounds great!

**Comment by waywardmonkeys** [comment]
This was resolved by your pull request #3, right?

**Comment by phillord** [comment]
Yes!
