### ISSUE TITLE
Use an indexed map to guarantee consistent IRI shrinking behaviour

### ISSUE THREAD

**Issue by althonos** [endoli/curie.rs#5]
Hi!

Since the `PrefixMapping` uses an `HashMap` internally, there is no guarantee about the iteration order, meaning with the current implementation of `shrink_iri` that if two prefixes are used for the same URI (or, that is, if there is ambiguity), there is no way to have a consistent behaviour.

Using for instance an [`IndexMap`](https://docs.rs/indexmap/1.0.2/indexmap/map/struct.IndexMap.html) would allow to keep the insertion order *as long as no prefix is removed*, providing *FIFO* semantics when shrinking IRIs.

**Comment by althonos** [comment]
@endoli: I can open a PR if you don't have time to work on this, it's not critical for my current project but I would be glad to have it at some point :wink:

**Comment by waywardmonkeys** [comment]
This has been published now in version 0.1.0.

If you'd like to submit a PR with tests for this ... that'd be great!
